"""Schema helpers shared by the data pipeline (merge / balance / validate).

Class IDs, group memberships, and per-dataset domains all come from
configs/schema.yaml — never hardcoded. Also regenerates configs/data.yaml from
the schema so the two can't drift.
"""

from __future__ import annotations

import logging
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

# src/data/schema_utils.py -> parents[2] is the repo root.
REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SCHEMA_PATH = REPO_ROOT / "configs" / "schema.yaml"
DEFAULT_DATA_YAML = REPO_ROOT / "configs" / "data.yaml"
DEFAULT_INTERIM_ROOT = REPO_ROOT / "data" / "interim"
DEFAULT_PROCESSED_ROOT = REPO_ROOT / "data" / "processed"

SURFACE = "surface"
AERIAL = "aerial"


def load_schema(schema_path: Path | str = DEFAULT_SCHEMA_PATH) -> dict:
    with open(schema_path, "r", encoding="utf-8") as fh:
        return yaml.safe_load(fh)


def id_to_name(schema: dict) -> dict[int, str]:
    return dict(schema["classes"])


def ordered_names(schema: dict) -> list[str]:
    classes = schema["classes"]
    return [classes[i] for i in sorted(classes)]


def num_classes(schema: dict) -> int:
    return len(schema["classes"])


def military_class_ids(schema: dict) -> set[int]:
    """Class IDs in the `military` group — the recall-gate classes."""
    return set(schema.get("groups", {}).get("military", []))


def dedup_config(schema: dict) -> dict:
    """Return the dedup {method, threshold} config, with conservative defaults."""
    cfg = schema.get("dedup") or {}
    return {
        "method": cfg.get("method", "greedy"),
        "threshold": int(cfg.get("threshold", 3)),
    }


def domain_for(schema: dict, dataset: str, default: str = SURFACE) -> str:
    """Return the visual domain for a source dataset, falling back to `default`."""
    domains = schema.get("domains") or {}
    if dataset not in domains:
        logger.warning(
            "dataset %r has no domain in schema.yaml; defaulting to %r",
            dataset, default,
        )
        return default
    return domains[dataset]


def _names_list(names) -> list[str]:
    """Normalize a data.yaml `names` (dict{id:name} or list) to an ordered list."""
    if isinstance(names, dict):
        return [names[i] for i in sorted(names)]
    return list(names)


def data_schema_problems(schema: dict, data: dict) -> list[str]:
    """Return human-readable drift between schema.yaml and data.yaml (empty=OK)."""
    schema_names = ordered_names(schema)
    problems: list[str] = []
    data_names = _names_list(data.get("names", []))
    if data_names != schema_names:
        problems.append(
            f"class lists differ:\n    schema: {schema_names}\n    data:   {data_names}"
        )
    if data.get("nc") != len(schema_names):
        problems.append(f"nc={data.get('nc')} != number of schema classes "
                        f"({len(schema_names)})")
    return problems


def write_data_yaml(
    schema: dict,
    out_path: Path | str = DEFAULT_DATA_YAML,
    processed_root: Path | str = "data/processed",
) -> None:
    """Regenerate configs/data.yaml from the schema so the two can't drift."""
    names = id_to_name(schema)
    lines = [
        "# =============================================================================",
        "# data.yaml — AUTO-GENERATED by src/data/merge.py from configs/schema.yaml.",
        "# Do NOT edit by hand: change schema.yaml and re-run merge (or",
        "# `python -m src.data.merge --data-yaml-only`). CI asserts these match.",
        "# =============================================================================",
        "",
        f"path: {processed_root}",
        "train: images/train",
        "val: images/val",
        "test: images/test",
        "",
        f"nc: {len(names)}",
        "",
        "names:",
    ]
    for cid in sorted(names):
        lines.append(f"  {cid}: {names[cid]}")
    Path(out_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("wrote %s (%d classes)", out_path, len(names))
